# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Simple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Simple.proto',
  package='Simple',
  syntax='proto3',
  serialized_pb=_b('\n\x0cSimple.proto\x12\x06Simple\x1a\x1cgoogle/api/annotations.proto\"T\n\x10SearchParameters\x12!\n\x02sm\x18\x01 \x01(\x0b\x32\x15.Simple.StringMessage\x12\x1d\n\x01p\x18\x02 \x01(\x0b\x32\x12.Simple.Classifier\"+\n\rStringMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"$\n\x06KVPair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"+\n\x07KVPairs\x12 \n\x08kv_pairs\x18\x01 \x03(\x0b\x32\x0e.Simple.KVPair\"\x9f\x01\n\nClassifier\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bruntime_url\x18\x02 \x01(\t\x12\x0f\n\x07\x63reator\x18\x03 \x01(\t\x12\x17\n\x0f\x63lassifier_type\x18\x04 \x01(\t\x12\x0f\n\x07\x63luster\x18\x05 \x01(\t\x12\x12\n\nname_space\x18\x06 \x01(\t\x12!\n\x08kv_pairs\x18\x07 \x01(\x0b\x32\x0f.Simple.KVPairs\"6\n\x0b\x43lassifiers\x12\'\n\x0b\x63lassifiers\x18\x01 \x03(\x0b\x32\x12.Simple.Classifier2\xd1\x01\n\x06Simple\x12\x62\n\x0eListClassifier\x12\x18.Simple.SearchParameters\x1a\x13.Simple.Classifiers\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/simple/listclassifier\x12\x63\n\x10\x43reateClassifier\x12\x12.Simple.Classifier\x1a\x13.Simple.Classifiers\"&\x82\xd3\xe4\x93\x02 \"\x1b/v1/simple/createclassifier:\x01*b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_SEARCHPARAMETERS = _descriptor.Descriptor(
  name='SearchParameters',
  full_name='Simple.SearchParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sm', full_name='Simple.SearchParameters.sm', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='p', full_name='Simple.SearchParameters.p', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=138,
)


_STRINGMESSAGE = _descriptor.Descriptor(
  name='StringMessage',
  full_name='Simple.StringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Simple.StringMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Simple.StringMessage.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=183,
)


_KVPAIR = _descriptor.Descriptor(
  name='KVPair',
  full_name='Simple.KVPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Simple.KVPair.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Simple.KVPair.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=221,
)


_KVPAIRS = _descriptor.Descriptor(
  name='KVPairs',
  full_name='Simple.KVPairs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kv_pairs', full_name='Simple.KVPairs.kv_pairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=266,
)


_CLASSIFIER = _descriptor.Descriptor(
  name='Classifier',
  full_name='Simple.Classifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Simple.Classifier.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runtime_url', full_name='Simple.Classifier.runtime_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creator', full_name='Simple.Classifier.creator', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classifier_type', full_name='Simple.Classifier.classifier_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cluster', full_name='Simple.Classifier.cluster', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name_space', full_name='Simple.Classifier.name_space', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kv_pairs', full_name='Simple.Classifier.kv_pairs', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=428,
)


_CLASSIFIERS = _descriptor.Descriptor(
  name='Classifiers',
  full_name='Simple.Classifiers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classifiers', full_name='Simple.Classifiers.classifiers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=484,
)

_SEARCHPARAMETERS.fields_by_name['sm'].message_type = _STRINGMESSAGE
_SEARCHPARAMETERS.fields_by_name['p'].message_type = _CLASSIFIER
_KVPAIRS.fields_by_name['kv_pairs'].message_type = _KVPAIR
_CLASSIFIER.fields_by_name['kv_pairs'].message_type = _KVPAIRS
_CLASSIFIERS.fields_by_name['classifiers'].message_type = _CLASSIFIER
DESCRIPTOR.message_types_by_name['SearchParameters'] = _SEARCHPARAMETERS
DESCRIPTOR.message_types_by_name['StringMessage'] = _STRINGMESSAGE
DESCRIPTOR.message_types_by_name['KVPair'] = _KVPAIR
DESCRIPTOR.message_types_by_name['KVPairs'] = _KVPAIRS
DESCRIPTOR.message_types_by_name['Classifier'] = _CLASSIFIER
DESCRIPTOR.message_types_by_name['Classifiers'] = _CLASSIFIERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchParameters = _reflection.GeneratedProtocolMessageType('SearchParameters', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHPARAMETERS,
  __module__ = 'Simple_pb2'
  # @@protoc_insertion_point(class_scope:Simple.SearchParameters)
  ))
_sym_db.RegisterMessage(SearchParameters)

StringMessage = _reflection.GeneratedProtocolMessageType('StringMessage', (_message.Message,), dict(
  DESCRIPTOR = _STRINGMESSAGE,
  __module__ = 'Simple_pb2'
  # @@protoc_insertion_point(class_scope:Simple.StringMessage)
  ))
_sym_db.RegisterMessage(StringMessage)

KVPair = _reflection.GeneratedProtocolMessageType('KVPair', (_message.Message,), dict(
  DESCRIPTOR = _KVPAIR,
  __module__ = 'Simple_pb2'
  # @@protoc_insertion_point(class_scope:Simple.KVPair)
  ))
_sym_db.RegisterMessage(KVPair)

KVPairs = _reflection.GeneratedProtocolMessageType('KVPairs', (_message.Message,), dict(
  DESCRIPTOR = _KVPAIRS,
  __module__ = 'Simple_pb2'
  # @@protoc_insertion_point(class_scope:Simple.KVPairs)
  ))
_sym_db.RegisterMessage(KVPairs)

Classifier = _reflection.GeneratedProtocolMessageType('Classifier', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFIER,
  __module__ = 'Simple_pb2'
  # @@protoc_insertion_point(class_scope:Simple.Classifier)
  ))
_sym_db.RegisterMessage(Classifier)

Classifiers = _reflection.GeneratedProtocolMessageType('Classifiers', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFIERS,
  __module__ = 'Simple_pb2'
  # @@protoc_insertion_point(class_scope:Simple.Classifiers)
  ))
_sym_db.RegisterMessage(Classifiers)



_SIMPLE = _descriptor.ServiceDescriptor(
  name='Simple',
  full_name='Simple.Simple',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=487,
  serialized_end=696,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListClassifier',
    full_name='Simple.Simple.ListClassifier',
    index=0,
    containing_service=None,
    input_type=_SEARCHPARAMETERS,
    output_type=_CLASSIFIERS,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\033\022\031/v1/simple/listclassifier')),
  ),
  _descriptor.MethodDescriptor(
    name='CreateClassifier',
    full_name='Simple.Simple.CreateClassifier',
    index=1,
    containing_service=None,
    input_type=_CLASSIFIER,
    output_type=_CLASSIFIERS,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002 \"\033/v1/simple/createclassifier:\001*')),
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMPLE)

DESCRIPTOR.services_by_name['Simple'] = _SIMPLE

# @@protoc_insertion_point(module_scope)
