# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.simple_kv_pair import SimpleKVPair  # noqa: F401,E501
from swagger_server import util


class SimpleKVPairs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, kv_pairs: List[SimpleKVPair]=None):  # noqa: E501
        """SimpleKVPairs - a model defined in Swagger

        :param kv_pairs: The kv_pairs of this SimpleKVPairs.  # noqa: E501
        :type kv_pairs: List[SimpleKVPair]
        """
        self.swagger_types = {
            'kv_pairs': List[SimpleKVPair]
        }

        self.attribute_map = {
            'kv_pairs': 'kv_pairs'
        }

        self._kv_pairs = kv_pairs

    @classmethod
    def from_dict(cls, dikt) -> 'SimpleKVPairs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SimpleKVPairs of this SimpleKVPairs.  # noqa: E501
        :rtype: SimpleKVPairs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kv_pairs(self) -> List[SimpleKVPair]:
        """Gets the kv_pairs of this SimpleKVPairs.


        :return: The kv_pairs of this SimpleKVPairs.
        :rtype: List[SimpleKVPair]
        """
        return self._kv_pairs

    @kv_pairs.setter
    def kv_pairs(self, kv_pairs: List[SimpleKVPair]):
        """Sets the kv_pairs of this SimpleKVPairs.


        :param kv_pairs: The kv_pairs of this SimpleKVPairs.
        :type kv_pairs: List[SimpleKVPair]
        """

        self._kv_pairs = kv_pairs
