# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.simple_kv_pairs import SimpleKVPairs  # noqa: F401,E501
from swagger_server import util


class SimpleClassifier(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, runtime_url: str=None, creator: str=None, classifier_type: str=None, cluster: str=None, name_space: str=None, kv_pairs: SimpleKVPairs=None):  # noqa: E501
        """SimpleClassifier - a model defined in Swagger

        :param id: The id of this SimpleClassifier.  # noqa: E501
        :type id: str
        :param runtime_url: The runtime_url of this SimpleClassifier.  # noqa: E501
        :type runtime_url: str
        :param creator: The creator of this SimpleClassifier.  # noqa: E501
        :type creator: str
        :param classifier_type: The classifier_type of this SimpleClassifier.  # noqa: E501
        :type classifier_type: str
        :param cluster: The cluster of this SimpleClassifier.  # noqa: E501
        :type cluster: str
        :param name_space: The name_space of this SimpleClassifier.  # noqa: E501
        :type name_space: str
        :param kv_pairs: The kv_pairs of this SimpleClassifier.  # noqa: E501
        :type kv_pairs: SimpleKVPairs
        """
        self.swagger_types = {
            'id': str,
            'runtime_url': str,
            'creator': str,
            'classifier_type': str,
            'cluster': str,
            'name_space': str,
            'kv_pairs': SimpleKVPairs
        }

        self.attribute_map = {
            'id': 'id',
            'runtime_url': 'runtime_url',
            'creator': 'creator',
            'classifier_type': 'classifier_type',
            'cluster': 'cluster',
            'name_space': 'name_space',
            'kv_pairs': 'kv_pairs'
        }

        self._id = id
        self._runtime_url = runtime_url
        self._creator = creator
        self._classifier_type = classifier_type
        self._cluster = cluster
        self._name_space = name_space
        self._kv_pairs = kv_pairs

    @classmethod
    def from_dict(cls, dikt) -> 'SimpleClassifier':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SimpleClassifier of this SimpleClassifier.  # noqa: E501
        :rtype: SimpleClassifier
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this SimpleClassifier.


        :return: The id of this SimpleClassifier.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this SimpleClassifier.


        :param id: The id of this SimpleClassifier.
        :type id: str
        """

        self._id = id

    @property
    def runtime_url(self) -> str:
        """Gets the runtime_url of this SimpleClassifier.


        :return: The runtime_url of this SimpleClassifier.
        :rtype: str
        """
        return self._runtime_url

    @runtime_url.setter
    def runtime_url(self, runtime_url: str):
        """Sets the runtime_url of this SimpleClassifier.


        :param runtime_url: The runtime_url of this SimpleClassifier.
        :type runtime_url: str
        """

        self._runtime_url = runtime_url

    @property
    def creator(self) -> str:
        """Gets the creator of this SimpleClassifier.


        :return: The creator of this SimpleClassifier.
        :rtype: str
        """
        return self._creator

    @creator.setter
    def creator(self, creator: str):
        """Sets the creator of this SimpleClassifier.


        :param creator: The creator of this SimpleClassifier.
        :type creator: str
        """

        self._creator = creator

    @property
    def classifier_type(self) -> str:
        """Gets the classifier_type of this SimpleClassifier.


        :return: The classifier_type of this SimpleClassifier.
        :rtype: str
        """
        return self._classifier_type

    @classifier_type.setter
    def classifier_type(self, classifier_type: str):
        """Sets the classifier_type of this SimpleClassifier.


        :param classifier_type: The classifier_type of this SimpleClassifier.
        :type classifier_type: str
        """

        self._classifier_type = classifier_type

    @property
    def cluster(self) -> str:
        """Gets the cluster of this SimpleClassifier.


        :return: The cluster of this SimpleClassifier.
        :rtype: str
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster: str):
        """Sets the cluster of this SimpleClassifier.


        :param cluster: The cluster of this SimpleClassifier.
        :type cluster: str
        """

        self._cluster = cluster

    @property
    def name_space(self) -> str:
        """Gets the name_space of this SimpleClassifier.


        :return: The name_space of this SimpleClassifier.
        :rtype: str
        """
        return self._name_space

    @name_space.setter
    def name_space(self, name_space: str):
        """Sets the name_space of this SimpleClassifier.


        :param name_space: The name_space of this SimpleClassifier.
        :type name_space: str
        """

        self._name_space = name_space

    @property
    def kv_pairs(self) -> SimpleKVPairs:
        """Gets the kv_pairs of this SimpleClassifier.


        :return: The kv_pairs of this SimpleClassifier.
        :rtype: SimpleKVPairs
        """
        return self._kv_pairs

    @kv_pairs.setter
    def kv_pairs(self, kv_pairs: SimpleKVPairs):
        """Sets the kv_pairs of this SimpleClassifier.


        :param kv_pairs: The kv_pairs of this SimpleClassifier.
        :type kv_pairs: SimpleKVPairs
        """

        self._kv_pairs = kv_pairs
