# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.simple_classifier import SimpleClassifier  # noqa: F401,E501
from swagger_server import util


class SimpleClassifiers(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, classifiers: List[SimpleClassifier]=None):  # noqa: E501
        """SimpleClassifiers - a model defined in Swagger

        :param classifiers: The classifiers of this SimpleClassifiers.  # noqa: E501
        :type classifiers: List[SimpleClassifier]
        """
        self.swagger_types = {
            'classifiers': List[SimpleClassifier]
        }

        self.attribute_map = {
            'classifiers': 'classifiers'
        }

        self._classifiers = classifiers

    @classmethod
    def from_dict(cls, dikt) -> 'SimpleClassifiers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SimpleClassifiers of this SimpleClassifiers.  # noqa: E501
        :rtype: SimpleClassifiers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def classifiers(self) -> List[SimpleClassifier]:
        """Gets the classifiers of this SimpleClassifiers.


        :return: The classifiers of this SimpleClassifiers.
        :rtype: List[SimpleClassifier]
        """
        return self._classifiers

    @classifiers.setter
    def classifiers(self, classifiers: List[SimpleClassifier]):
        """Sets the classifiers of this SimpleClassifiers.


        :param classifiers: The classifiers of this SimpleClassifiers.
        :type classifiers: List[SimpleClassifier]
        """

        self._classifiers = classifiers
